openapi: 3.1.0
info:
  title: openapi
  version: '1.0'
servers:
  - url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-user
    post:
      summary: User
      operationId: post-user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        name:
          type: string
          description: ユーザー名
        email:
          type: string
          description: メールアドレス
        password:
          type: string
          description: パスワード
      required:
        - name
        - email
        - password
