name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"

      - name: composer install
        run: docker run --rm -u "$(id -u):$(id -g)" -v $(pwd):/var/www/html -w /var/www/html laravelsail/php81-composer:latest composer install --ignore-platform-reqs

      - name: start mysql
        run: ./vendor/bin/sail up -d mysql

      - name: start
        run: ./vendor/bin/sail up -d

      - name: generate key
        run: ./vendor/bin/sail artisan key:generate

      - name: migrate
        run: ./vendor/bin/sail artisan migrate

      - name: php-cs-fixer
        run: ./vendor/bin/sail php ./vendor/bin/php-cs-fixer fix  --dry-run  --config=.php-cs.dist .

      - name: test
        run: ./vendor/bin/sail test
